In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
import pandas as pd
import numpy as np

In [4]:
pip install matplotlib 

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
     ---------------------------------------- 0.0/165.9 kB ? eta -:--:--
     --------- --------------------------- 41.0/165.9 kB 991.0 kB/s eta 0:00:01
     -------------------------------------  163.8/165.9 kB 3.3 MB/s eta 0:00:01
     -------------------------------------  163.8/165.9 kB 3.3 MB/s eta 0:00:01
     -------------------------------------- 165.9/165.9 kB 1.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/7.8 MB ? eta -:--:--
   -- ------------------------------------- 0.4/7.8 MB 8.9 MB/s eta 0:00:01
   ---- ----------------------------------- 0.9/7.8 MB 9.8 MB/s eta 0:00:01
   ------- -------------------------------- 1.5/7.8 MB 11.0 MB/s eta 0:00:01
   ----------- ---------------------------- 2.3/7.8 MB 12.3 MB/s eta 0:00:01
   ---------------- ----------------------- 3.3/7.8 MB 14.0 MB/s eta 0:00:01
   ---------------------- ----------------- 4.4/7.8 MB 15.8 MB/s eta 0:00:01
   -----------

In [5]:
pip install seaborn

  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [7]:
pip install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
dataset = pd.read_excel("C:/Users/aedpu/Downloads/student_dataset (5).xlsx")

In [5]:
dataset.head()

S.NO  ATTN  THEORY  Daily assn  TOTAL  certificate
0     1    20      38          25     83  DISTINCTION
1     2    15      25           0     40   COMPLETION
2     3    20      31          25     76  FIRST CLASS
3     4    20      25          25     70  FIRST CLASS
4     5    20      17          15     52  FIRST CLASS

In [6]:
dataset.shape

(367, 6)

In [7]:
dataset.describe()

S.NO        ATTN      THEORY  Daily assn       TOTAL
count  367.000000  367.000000  367.000000  367.000000  367.000000
mean   184.000000   18.926431   12.495913   13.405995   41.231608
std    106.088014    3.607450   12.815605    9.770943   21.568883
min      1.000000    1.000000    0.000000    0.000000    0.000000
25%     92.500000   15.000000    0.000000    0.000000   25.000000
50%    184.000000   20.000000   12.000000   15.000000   40.000000
75%    275.500000   20.000000   24.000000   25.000000   57.500000
max    367.000000   25.000000   42.000000   25.000000   87.000000

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   S.NO         367 non-null    int64 
 1   ATTN         367 non-null    int64 
 2   THEORY       367 non-null    int64 
 3   Daily assn   367 non-null    int64 
 4   TOTAL        367 non-null    int64 
 5   certificate  367 non-null    object
dtypes: int64(5), object(1)
memory usage: 17.3+ KB


In [9]:
data=dataset.drop(['S.NO','TOTAL'],axis=1)

In [10]:
data

ATTN  THEORY  Daily assn    certificate
0      20      38          25    DISTINCTION
1      15      25           0     COMPLETION
2      20      31          25    FIRST CLASS
3      20      25          25    FIRST CLASS
4      20      17          15    FIRST CLASS
..    ...     ...         ...            ...
362    15       0          10  PARTICIPATION
363    20       9          25     COMPLETION
364    15      20          25    FIRST CLASS
365    15       0          10  PARTICIPATION
366    20      23          10     COMPLETION

[367 rows x 4 columns]

In [11]:
data['certificate'].unique()

array(['DISTINCTION', 'COMPLETION', 'FIRST CLASS', 'PARTICIPATION'],
      dtype=object)

In [12]:
data.groupby('certificate').size()

certificate
COMPLETION       117
DISTINCTION       32
FIRST CLASS       66
PARTICIPATION    152
dtype: int64

In [3]:
pip install scikit-learn

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
data.iloc[:,3] = LabelEncoder().fit_transform(data.iloc[:,3])

In [15]:
data

ATTN  THEORY  Daily assn certificate
0      20      38          25           1
1      15      25           0           0
2      20      31          25           2
3      20      25          25           2
4      20      17          15           2
..    ...     ...         ...         ...
362    15       0          10           3
363    20       9          25           0
364    15      20          25           2
365    15       0          10           3
366    20      23          10           0

[367 rows x 4 columns]

In [16]:
x=data.iloc[:,:-1].values

In [17]:
x

array([[20, 38, 25],
       [15, 25,  0],
       [20, 31, 25],
       ...,
       [15, 20, 25],
       [15,  0, 10],
       [20, 23, 10]])

In [18]:
data

ATTN  THEORY  Daily assn certificate
0      20      38          25           1
1      15      25           0           0
2      20      31          25           2
3      20      25          25           2
4      20      17          15           2
..    ...     ...         ...         ...
362    15       0          10           3
363    20       9          25           0
364    15      20          25           2
365    15       0          10           3
366    20      23          10           0

[367 rows x 4 columns]

In [19]:
pip show scikit-learn

Name: scikit-learn
Version: 1.5.1
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: C:\Users\aedpu\anaconda3\envs\RasikCSE\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip show numpy

Name: numpy
Version: 2.0.1
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2024, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRI

In [19]:
data

ATTN  THEORY  Daily assn certificate
0      20      38          25           1
1      15      25           0           0
2      20      31          25           2
3      20      25          25           2
4      20      17          15           2
..    ...     ...         ...         ...
362    15       0          10           3
363    20       9          25           0
364    15      20          25           2
365    15       0          10           3
366    20      23          10           0

[367 rows x 4 columns]

In [20]:
y =data.iloc[:,3].values

In [21]:
y

array([1, 0, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 3, 0, 0, 2, 0, 2, 1,
       2, 3, 1, 0, 3, 1, 2, 1, 0, 0, 0, 3, 2, 0, 0, 0, 1, 2, 1, 0, 1, 1,
       2, 0, 0, 0, 3, 0, 1, 2, 2, 2, 0, 3, 0, 2, 0, 1, 2, 2, 2, 1, 0, 3,
       1, 0, 3, 3, 0, 3, 1, 3, 0, 0, 3, 3, 3, 3, 1, 0, 2, 0, 3, 3, 0, 3,
       3, 2, 3, 3, 3, 2, 2, 0, 2, 0, 0, 1, 0, 1, 1, 2, 1, 2, 3, 1, 0, 3,
       3, 1, 3, 0, 3, 0, 0, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 0, 0, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 1, 0, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       0, 0, 0, 3, 3, 3, 3, 3, 3, 0, 3, 0, 1, 1, 0, 2, 0, 2, 0, 2, 0, 0,
       2, 0, 0, 3, 0, 0, 2, 0, 2, 2, 0, 3, 1, 3, 0, 2, 0, 1, 0, 0, 0, 2,
       2, 2, 0, 2, 2, 2, 0, 2, 2, 3, 0, 1, 3, 2, 3, 3, 1, 2, 1, 0, 3, 2,
       2, 2, 2, 3, 0, 0, 3, 3, 3, 0, 0, 0, 3, 3, 0, 3, 2, 0, 3, 3, 0, 3,
       3, 3, 0, 3, 0, 3, 3, 3, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 0, 0, 3,
       0, 0, 3, 0, 0, 3, 3, 2, 3, 3, 3, 0, 0, 3, 0,

In [22]:
x_frame=pd.DataFrame(x,columns=['Attn','Theory','Daily Assn'])

In [23]:
x_frame

Attn  Theory  Daily Assn
0      20      38          25
1      15      25           0
2      20      31          25
3      20      25          25
4      20      17          15
..    ...     ...         ...
362    15       0          10
363    20       9          25
364    15      20          25
365    15       0          10
366    20      23          10

[367 rows x 3 columns]

In [36]:
y_frame=pd.DataFrame(y_transformed)

In [37]:
y_frame

0
0    1
1    0
2    2
3    2
4    2
..  ..
362  3
363  0
364  2
365  3
366  0

[367 rows x 1 columns]

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x_frame,y_frame,test_size=0.2,random_state=0)

In [40]:
x_train

Attn  Theory  Daily Assn
63     25      36          25
241    25      21          25
306    15       0           0
317    20      21          10
245    15       0           0
..    ...     ...         ...
323    20       7          25
192    20       0          25
117    20      16           0
47     20      22          15
172    15       0           0

[293 rows x 3 columns]

In [41]:
x_test

Attn  Theory  Daily Assn
106    15       0          15
259    20      27          15
45     20       0          20
26     15       0           0
78     15       0           0
..    ...     ...         ...
159    15       0           0
74     20      16          15
170    20       0           0
114    15       0           0
295    20      19          15

[74 rows x 3 columns]

In [42]:
y_train

0
63   1
241  2
306  3
317  0
245  3
..  ..
323  0
192  0
117  3
47   0
172  3

[293 rows x 1 columns]

In [43]:
y_test

0
106  3
259  0
45   0
26   3
78   3
..  ..
159  3
74   0
170  3
114  3
295  3

[74 rows x 1 columns]

In [44]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
knn = KNeighborsClassifier(n_neighbors=5)

In [46]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [47]:
lab = sklearn.preprocessing.LabelEncoder()

In [48]:
import sklearn

In [49]:
y_transformed = lab.fit_transform(y)

In [50]:
y_predict = knn.predict(x_test)

In [51]:
y_predict

array([3, 2, 0, 3, 3, 3, 3, 3, 0, 0, 3, 0, 0, 2, 0, 1, 0, 2, 1, 3, 3, 0,
       1, 0, 3, 3, 3, 0, 0, 2, 3, 2, 3, 3, 0, 0, 2, 3, 3, 0, 0, 3, 0, 3,
       0, 0, 0, 0, 3, 3, 3, 2, 0, 1, 3, 0, 0, 3, 2, 0, 2, 0, 1, 0, 3, 0,
       0, 3, 0, 3, 0, 3, 3, 0])

In [52]:
knn.score(x_train,y_train)

0.7849829351535836

In [53]:
knn.score(x_test,y_test)

0.6891891891891891

In [54]:
from sklearn.metrics import confusion_matrix

In [55]:
con_matrix = confusion_matrix(y_test,y_predict)

In [56]:
con_matrix

array([[15,  0,  2,  1],
       [ 0,  3,  2,  0],
       [ 7,  2,  5,  0],
       [ 9,  0,  0, 28]])