In [1]:
pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.9 kB 660.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 660.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 270.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   - -------------------------------------- 0.6/16.6 MB 17.6 MB/s eta 0:00:01
   --- ------------------------------------ 1.5/16.6 MB 19.6 MB/s eta 0:00:01
   ----- ---------------------------------- 2.4/16.6 MB 19.2 MB/s eta 0:00:01
   ------- -------------------------------- 3.3/16.6 MB 19.0 MB/s eta 0:00:01
   ---------- ----------------------------- 4.1/16.6 MB 18.9 MB/s eta 0:00:01
   ------------ --------------------------- 5.1/16.6 MB 19.0 MB/s eta 0:00:01
   -------------- ------------------------- 5.9/16.6 MB 18.9 MB/s eta 

In [2]:
pip install pandas

  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   -- ------------------------------------- 0.6/11.6 MB 12.5 MB/s eta 0:00:01
   --- ------------------------------------ 1.0/11.6 MB 10.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.5/11.6 MB 11.8 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.6 MB 12.0 MB/s eta 0:00:01
   --------- ------------------------------ 2.7/11.6 MB 11.3 MB/s eta 0:00:01
   ----------- ---------------------------- 3.4/11.6 MB 12.8 MB/s eta 0:00:01
   -------------- ------------------------- 4.3/11.6 MB 13.1 MB/s eta 0:00:01
   ----------------- ---------------------- 5.2/11.6 MB 13.9 MB/s eta 0:00:01
   --------------------- ------------------ 6.2/11.6 MB 15.2 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.6 MB 15.2 MB/s eta 0:00:01
   --------------------------- ------------ 8.0/11.6 MB 15.6 MB/s eta 0:00:01
   -

In [1]:
import numpy as np

In [2]:
np.version.version

'2.0.1'


# array

In [3]:
first_array = np.array([1,2,3])

In [4]:
print(first_array)

[1 2 3]


In [5]:
type(first_array)

numpy.ndarray

In [6]:
sec_array = np.array([1,2.0,345])

In [7]:
sec_array

array([  1.,   2., 345.])

In [8]:
type(sec_array)

numpy.ndarray

In [9]:
trid_array = np.array([(2,3,4),(5,6,7)])

In [10]:
print(trid_array)

[[2 3 4]
 [5 6 7]]


In [11]:
tree_array = np.array([[(2,34,4),(2,4,6)],[(3,4,5),(7,8,9)]])

In [12]:
print(tree_array)

[[[ 2 34  4]
  [ 2  4  6]]

 [[ 3  4  5]
  [ 7  8  9]]]


In [15]:
zero_array = np.zeros((9,8))

In [16]:
print(zero_array)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
ones_array = np.ones((9,8))

In [18]:
print(ones_array)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
spaced_num = np.linspace(0,35,25)

In [20]:
print(spaced_num)

[ 0.          1.45833333  2.91666667  4.375       5.83333333  7.29166667
  8.75       10.20833333 11.66666667 13.125      14.58333333 16.04166667
 17.5        18.95833333 20.41666667 21.875      23.33333333 24.79166667
 26.25       27.70833333 29.16666667 30.625      32.08333333 33.54166667
 35.        ]


In [21]:
my_array = np.array([1,2,3])

In [22]:
print(my_array)

[1 2 3]


In [23]:
arr_ones = np.ones((2,2))

In [24]:
print(arr_ones)

[[1. 1.]
 [1. 1.]]


In [25]:
my_matrix = np.array([(11,23,45),(34,56,78)])

In [26]:
print(my_matrix)

[[11 23 45]
 [34 56 78]]


In [27]:
matrix_transpose = np.transpose(my_matrix)

In [29]:
print(matrix_transpose)

[[11 34]
 [23 56]
 [45 78]]


In [30]:
matrix_transpose.ravel()

array([11, 34, 23, 56, 45, 78])

In [1]:
import pandas as pd

In [2]:
pd._version_

AttributeError: module 'pandas' has no attribute '_version_'

In [3]:
pd.__version__

'2.2.2'

In [2]:
a1=pd.series(['rakshana','guptha','santhiya','guhan','rasik'],index=[0,1,2,3,4])

AttributeError: module 'pandas' has no attribute 'series'